server:
  port: 8011



eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka,http://eureka7002.com:7002/eureka
  instance:
    instance-id: payment-8011
    prefer-ip-address: true



spring:
  application:
    name: cloud-provider-hystrix-payment
#  cloud:
#    circuitbreaker:
#      hystrix:
#        enabled: true


