spring:
  application:
    name: cloud-stream-consumer
  cloud:
    stream:
      #      default-binder: localRabbit
      binders: # 在此处配置要绑定的rabbitmq的服务信息； 可以配置多个 配置多个时候就得排配置默认的 default-binder
        localRabbit: # 表示定义的名称，用于于binding整合
        type: rabbit # 消息组件类型
        environment: # 设置rabbitmq的相关的环境配置
        spring:
        rabbitmq:
        host: localhost
        port: 5672
        username: guest
        password: guest
      bindings: # 服务的整合处理
        input: # 这个名字是一个通道的名称
        destination: studyExchange # 表示要使用的Exchange名称定义
        content-type: application/json # 设置消息类型，本次为对象json，如果是文本则设置“text/plain”
        binder: localRabbit # 设置要绑定的消息服务的具体设置