server:
  port: 8803

spring:
  application:
    name: cloud-stream-consumer

eureka:
  client:
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka,http://eureka7002.com:7002/eureka
  instance:
    instance-id: receive-8803
    prefer-ip-address: true
    lease-renewal-interval-in-seconds: 2 # 设置心跳的间隔时间 默认30s
    lease-expiration-duration-in-seconds: 5 #如果超过5秒 剔除

---
spring:
  profiles:
    active: dy
