server:
  port: 9527

eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka,http://eureka7002.com:7002/eureka
  instance:
    hostname: gateway  # 虚拟域名 host里面配置了 127.0.0.1       gateway
    instance-id: gateway-9527
    prefer-ip-address: true



spring:
  application:
    name: cloud-gateway

    # GATEWAY

  cloud:
    gateway:
      discovery:
        locator:
          enabled: true # 开启从注册中心动态创建路由的功能，利用微服务进行路由
      routes:
        - id: payment_routh  # 路由的ID 没有固定固定规则 但是要求唯一
          #uri: http://localhost:8001  直接配置路径
          uri: lb://cloud-payment-service   #匹配后提供服务的路由地址
          predicates:
            - Path=/api/payment/**   # 断言，路径相匹配的进行路由