server:
  port: 3366

spring:
  application:
    name: config-client


# 服务注册
eureka:
  client:
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka,http://eureka7002.com:7002/eureka
  instance:
    instance-id: ${spring.application.name}:${server.port}
    prefer-ip-address: true


# 暴露刷新监控端点
management:
  endpoints:
    web:
      exposure:
        include: "refresh"