spring:
  cloud:
    stream:
      binders: # 在此处配置要绑定的rabbitMq服务信息
        localRabbit:  # 表示定义的名称，用于于binding整合
          type: rabbit # 消息组件类型
          environment: # 设置rabbitmq的相关的环境配置
            spring:
              rabbitmq:
                host: localhost
                port: 5672
                username: guest
                password: guest
      bindings:  # 服务的整合处理
        dyOutPutTopic: # 这个名字是一个通道的名字
          destination: studyExchangeTopic # 表示要使用的Exchange名称定义
          content-type: application/json # 设置消息类型，本次为json，文本则设置“text/plain”
          binder: localRabbit # 设置要绑定的消息服务的具体设置

        dyOutPutDirect: # 这个名字是一个通道的名字
          destination: studyExchangeDirect # 表示要使用的Exchange名称定义
          #          exchangeType: direct 这里不生效 在下面rabbit配置
          content-type: application/json # 设置消息类型，本次为json，文本则设置“text/plain”
          binder: localRabbit # 设置要绑定的消息服务的具体设置
          #rabbit 配置
      rabbit:
        bindings:
          dyOutPutDirect:
            producer:
              exchangeType: direct
              routingKeyExpression: '''study-key'''